import {
  ArrowDownOutline,
  ArrowLeftOutline,
  ArrowRightOutline,
  ArrowUpOutline,
  CheckOutline,
  CloseOutline,
  DeleteOutline,
  EditOutline,
  ExceptionOutline,
  ExperimentOutline,
  FilterFill,
  InboxOutline,
  InfoCircleFill,
  MoreOutline,
  PieChartOutline,
  PlusCircleOutline,
  SearchOutline,
  SettingOutline,
  SyncOutline,
  TagsOutline,
  UndoOutline,
  UnorderedListOutline,
  UploadOutline,
  WalletOutline,
  WarningOutline,
} from '@ant-design/icons-angular/icons';

/**
 * Ikony rejestrujemy jawnie, bo NG-ZORRO wpięliśmy bez trybu dynamicznego.
 * Brak wpisu tutaj = błąd w runtime („icon ... is not registered"), nie błąd kompilacji,
 * więc dodając nową ikonę w szablonie dopisz ją TAKŻE tutaj.
 */
export const APP_ICONS = [
  ArrowDownOutline,
  ArrowLeftOutline,
  ArrowRightOutline,
  ArrowUpOutline,
  CheckOutline,
  CloseOutline,
  DeleteOutline,
  EditOutline,
  ExceptionOutline,
  ExperimentOutline,
  FilterFill,
  InboxOutline,
  InfoCircleFill,
  MoreOutline,
  PieChartOutline,
  PlusCircleOutline,
  SearchOutline,
  SettingOutline,
  SyncOutline,
  TagsOutline,
  UndoOutline,
  UnorderedListOutline,
  UploadOutline,
  WalletOutline,
  WarningOutline,
];
