// <auto-generated />
using System;
using System.Collections.Generic;
using BudgetTracker.Api.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BudgetTracker.Api.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BudgetTracker.Api.Domain.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId")
                        .IsUnique();

                    b.HasIndex("Type");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("BudgetTracker.Api.Domain.AccountTypeDictionary", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Code");

                    b.ToTable("AccountTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "Bank"
                        },
                        new
                        {
                            Code = "LunchCard"
                        },
                        new
                        {
                            Code = "Cash"
                        });
                });

            modelBuilder.Entity("BudgetTracker.Api.Domain.Budget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz");

                    b.Property<DateTimeOffset?>("DisabledAt")
                        .HasColumnType("timestamptz");

                    b.Property<decimal>("InitialBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid?>("LinkedSavingsBudgetBusinessId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Month")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.ComplexCollection(typeof(List<Dictionary<string, object>>), "SavingsTransferRules", "BudgetTracker.Api.Domain.Budget.SavingsTransferRules#TitleAmountRule", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("AmountFrom");

                            b1.Property<decimal>("AmountTo");

                            b1.Property<string>("TitlePattern")
                                .IsRequired();

                            b1
                                .ToJson("SavingsTransferRules")
                                .HasColumnType("jsonb");
                        });

                    b.HasKey("Id");

                    b.HasIndex("BusinessId")
                        .IsUnique();

                    b.HasIndex("Currency");

                    b.HasIndex("UserId");

                    b.ToTable("Budgets");
                });

            modelBuilder.Entity("BudgetTracker.Api.Domain.BudgetItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("BudgetBusinessId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uuid");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz");

                    b.Property<decimal>("Limit")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ValidTo")
                        .HasColumnType("date");

                    b.Property<int>("WarningThreshold")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId")
                        .IsUnique();

                    b.HasIndex("CategoryId");

                    b.HasIndex("BudgetBusinessId", "CategoryId", "ValidFrom")
                        .IsUnique()
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.ToTable("BudgetItems");
                });

            modelBuilder.Entity("BudgetTracker.Api.Domain.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("BudgetTracker.Api.Domain.CategoryRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uuid");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("MaxAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("MinAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Note")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Pattern")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("TransactionTypePattern")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId")
                        .IsUnique();

                    b.HasIndex("CategoryId");

                    b.HasIndex("Direction");

                    b.HasIndex("Priority");

                    b.ToTable("CategoryRules");
                });

            modelBuilder.Entity("BudgetTracker.Api.Domain.Currency", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.HasKey("Code");

                    b.ToTable("Currencies");

                    b.HasData(
                        new
                        {
                            Code = "PLN"
                        });
                });

            modelBuilder.Entity("BudgetTracker.Api.Domain.EpisodicOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("BudgetBusinessId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uuid");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateOnly?>("DueMonth")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("PlannedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid?>("ReservationBusinessId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TransactionBusinessId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BudgetBusinessId");

                    b.HasIndex("BusinessId")
                        .IsUnique();

                    b.HasIndex("CategoryId");

                    b.HasIndex("TransactionBusinessId")
                        .IsUnique()
                        .HasFilter("\"TransactionBusinessId\" IS NOT NULL AND \"DeletedAt\" IS NULL");

                    b.ToTable("EpisodicOrders");
                });

            modelBuilder.Entity("BudgetTracker.Api.Domain.ImportBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Bank")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int>("BudgetId")
                        .HasColumnType("integer");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");

                    b.Property<DateTimeOffset>("ImportedAt")
                        .HasColumnType("timestamptz");

                    b.Property<int>("ImportedCount")
                        .HasColumnType("integer");

                    b.Property<int>("PendingReviewCount")
                        .HasColumnType("integer");

                    b.Property<int>("RowCount")
                        .HasColumnType("integer");

                    b.Property<int>("SkippedDuplicateCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BudgetId");

                    b.HasIndex("BusinessId")
                        .IsUnique();

                    b.ToTable("ImportBatches");
                });

            modelBuilder.Entity("BudgetTracker.Api.Domain.RuleDirectionDictionary", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Code");

                    b.ToTable("RuleDirections", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "Any"
                        },
                        new
                        {
                            Code = "Expense"
                        },
                        new
                        {
                            Code = "Income"
                        });
                });

            modelBuilder.Entity("BudgetTracker.Api.Domain.SavingsGoal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("BudgetBusinessId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz");

                    b.Property<DateOnly?>("EndedOn")
                        .HasColumnType("date");

                    b.Property<DateOnly>("StartedOn")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId")
                        .IsUnique();

                    b.HasIndex("BudgetBusinessId", "StartedOn");

                    b.ToTable("SavingsGoals");
                });

            modelBuilder.Entity("BudgetTracker.Api.Domain.SavingsReservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("BudgetBusinessId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz");

                    b.Property<DateOnly?>("DueMonth")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("SettledAt")
                        .HasColumnType("timestamptz");

                    b.Property<Guid?>("SettledTransactionBusinessId")
                        .HasColumnType("uuid");

                    b.ComplexCollection(typeof(List<Dictionary<string, object>>), "Contributions", "BudgetTracker.Api.Domain.SavingsReservation.Contributions#SavingsContribution", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount");

                            b1.Property<DateOnly>("Date");

                            b1.Property<Guid>("Id");

                            b1
                                .ToJson("Contributions")
                                .HasColumnType("jsonb");
                        });

                    b.HasKey("Id");

                    b.HasIndex("BusinessId")
                        .IsUnique();

                    b.HasIndex("SettledTransactionBusinessId")
                        .IsUnique()
                        .HasFilter("\"SettledTransactionBusinessId\" IS NOT NULL AND \"DeletedAt\" IS NULL");

                    b.HasIndex("BudgetBusinessId", "DueMonth", "Priority");

                    b.ToTable("SavingsReservations");
                });

            modelBuilder.Entity("BudgetTracker.Api.Domain.StandingOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("BudgetBusinessId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz");

                    b.Property<int?>("DueMonth")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("EndMonth")
                        .HasColumnType("date");

                    b.Property<decimal>("ExpectedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Rhythm")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.ComplexCollection(typeof(List<Dictionary<string, object>>), "Rules", "BudgetTracker.Api.Domain.StandingOrder.Rules#StandingOrderRule", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("AmountFrom");

                            b1.Property<decimal>("AmountTo");

                            b1.Property<string>("TitlePattern")
                                .IsRequired();

                            b1
                                .ToJson("Rules")
                                .HasColumnType("jsonb");
                        });

                    b.HasKey("Id");

                    b.HasIndex("BudgetBusinessId");

                    b.HasIndex("BusinessId")
                        .IsUnique();

                    b.HasIndex("Rhythm");

                    b.ToTable("StandingOrders");
                });

            modelBuilder.Entity("BudgetTracker.Api.Domain.StandingOrderRhythmDictionary", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Code");

                    b.ToTable("StandingOrderRhythms", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "Monthly"
                        },
                        new
                        {
                            Code = "Quarterly"
                        },
                        new
                        {
                            Code = "Yearly"
                        });
                });

            modelBuilder.Entity("BudgetTracker.Api.Domain.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AccountId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid?>("BudgetBusinessId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uuid");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Confidence")
                        .HasPrecision(4, 3)
                        .HasColumnType("numeric(4,3)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ExternalReference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("ImportBatchId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SavingsTransferBudgetBusinessId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SavingsTransferUnpinnedFrom")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("StandingOrderBusinessId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("StandingOrderUnpinnedFrom")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("BudgetBusinessId");

                    b.HasIndex("BusinessId")
                        .IsUnique();

                    b.HasIndex("CategoryId");

                    b.HasIndex("ImportBatchId");

                    b.HasIndex("SavingsTransferBudgetBusinessId");

                    b.HasIndex("StandingOrderBusinessId");

                    b.HasIndex("Status");

                    b.HasIndex("Date", "CategoryId");

                    b.HasIndex("Date", "Amount", "ExternalReference");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("BudgetTracker.Api.Domain.TransactionStatusDictionary", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Code");

                    b.ToTable("TransactionStatuses", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "Imported"
                        },
                        new
                        {
                            Code = "AutoCategorized"
                        },
                        new
                        {
                            Code = "PendingReview"
                        },
                        new
                        {
                            Code = "ManuallyCategorized"
                        },
                        new
                        {
                            Code = "Confirmed"
                        });
                });

            modelBuilder.Entity("BudgetTracker.Api.Domain.Account", b =>
                {
                    b.HasOne("BudgetTracker.Api.Domain.AccountTypeDictionary", null)
                        .WithMany()
                        .HasForeignKey("Type")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BudgetTracker.Api.Domain.Budget", b =>
                {
                    b.HasOne("BudgetTracker.Api.Domain.Currency", null)
                        .WithMany()
                        .HasForeignKey("Currency")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BudgetTracker.Api.Domain.BudgetItem", b =>
                {
                    b.HasOne("BudgetTracker.Api.Domain.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BudgetTracker.Api.Domain.CategoryRule", b =>
                {
                    b.HasOne("BudgetTracker.Api.Domain.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BudgetTracker.Api.Domain.RuleDirectionDictionary", null)
                        .WithMany()
                        .HasForeignKey("Direction")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BudgetTracker.Api.Domain.EpisodicOrder", b =>
                {
                    b.HasOne("BudgetTracker.Api.Domain.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("BudgetTracker.Api.Domain.ImportBatch", b =>
                {
                    b.HasOne("BudgetTracker.Api.Domain.Budget", null)
                        .WithMany()
                        .HasForeignKey("BudgetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BudgetTracker.Api.Domain.StandingOrder", b =>
                {
                    b.HasOne("BudgetTracker.Api.Domain.StandingOrderRhythmDictionary", null)
                        .WithMany()
                        .HasForeignKey("Rhythm")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BudgetTracker.Api.Domain.Transaction", b =>
                {
                    b.HasOne("BudgetTracker.Api.Domain.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BudgetTracker.Api.Domain.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BudgetTracker.Api.Domain.ImportBatch", null)
                        .WithMany()
                        .HasForeignKey("ImportBatchId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BudgetTracker.Api.Domain.TransactionStatusDictionary", null)
                        .WithMany()
                        .HasForeignKey("Status")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
